export const 
  GET_INSTAGRAM_FEED_START = 'GET_INSTAGRAM_FEED_START',
  GET_INSTAGRAM_FEED_SUCCESS = 'GET_INSTAGRAM_FEED_SUCCESS',
  GET_INSTAGRAM_FEED_ERROR = 'GET_INSTAGRAM_FEED_ERROR',
  GET_INSTAGRAM_FEED_END = 'GET_INSTAGRAM_FEED_END'