export const 
  GET_INSTAGRAM_FEED_START = 'GET_INSTAGRAM_FEED_START',
  GET_INSTAGRAM_FEED_SUCCESS = 'GET_INSTAGRAM_FEED_SUCCESS',
  GET_INSTAGRAM_FEED_ERROR = 'GET_INSTAGRAM_FEED_ERROR',
  GET_INSTAGRAM_FEED_END = 'GET_INSTAGRAM_FEED_END',
  SUBMIT_CONTACT_FORM_START = 'SUBMIT_CONTACT_FORM_START',
  SUBMIT_CONTACT_FORM_SUCCESS = 'SUBMIT_CONTACT_FORM_SUCCESS',
  SUBMIT_CONTACT_FORM_ERROR = 'SUBMIT_CONTACT_FORM_ERROR',
  SUBMIT_CONTACT_FORM_END = 'SUBMIT_CONTACT_FORM_END'